apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::188228848053:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NVH3W3BXJTLG
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
      - system:masters
      rolearn: arn:aws:iam::188228848053:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-27T03:51:27Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2020-11-27T03:51:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1475"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 46b5fc92-7276-464d-a271-f783eb826602
